config/routes.rb
Rails.application.routes.draw do
  resources :engineers
  root to: "top#index"
  get 'about', to: 'about#index'
  resources :companies
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company.rb
class Company < ApplicationRecord
end

app/models/engineer.rb
class Engineer < ApplicationRecord
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
    @companies = Company.all
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :info, :zip)
    end
end

app/controllers/engineers_controller.rb
class EngineersController < ApplicationController
  before_action :set_engineer, only: [:show, :edit, :update, :destroy]

  # GET /engineers
  # GET /engineers.json
  def index
    @engineers = Engineer.all
  end

  # GET /engineers/1
  # GET /engineers/1.json
  def show
  end

  # GET /engineers/new
  def new
    @engineer = Engineer.new
  end

  # GET /engineers/1/edit
  def edit
    @engineer = Engineer.find(params[:id])
  end

  # POST /engineers
  # POST /engineers.json
  def create
    @engineer = Engineer.new(engineer_params)

    respond_to do |format|
      if @engineer.save
        format.html { redirect_to @engineer, notice: 'Engineer was successfully created.' }
        format.json { render :show, status: :created, location: @engineer }
      else
        format.html { render :new }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /engineers/1
  # PATCH/PUT /engineers/1.json
  def update
    respond_to do |format|
      if @engineer.update(engineer_params)
        format.html { redirect_to @engineer, notice: 'Engineer was successfully updated.' }
        format.json { render :show, status: :ok, location: @engineer }
      else
        format.html { render :edit }
        format.json { render json: @engineer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /engineers/1
  # DELETE /engineers/1.json
  def destroy
    @engineer.destroy
    respond_to do |format|
      format.html { redirect_to engineers_url, notice: 'Engineer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_engineer
      @engineer = Engineer.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def engineer_params
      params.require(:engineer).permit(:name, :company, :introducton)
    end
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def index
  end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/helpers/engineers_helper.rb
module EngineersHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/views/about/index.html.slim
h1 PoINfoとは
p サービス紹介説明

app/views/companies/_form.html.slim
= form_for @company do |f|
  - if @company.errors.any?
    #error_explanation
      h2 = "#{pluralize(@company.errors.count, "error")} prohibited this engineer from being saved:"
      ul
        - @company.errors.full_messages.each do |message|
          li = message
  .input-group.mb-3
    .input-group-prepend
      span.input-group-text 社名
    = f.text_field :name, class: "form-control"
  .input-group.mb-3
    .input-group-prepend
      span#inputGroup-sizing-default.input-group-text 住所
    = f.text_field :zip, class: "form-control"
  .form-group
    label 情報
    = f.text_area :info, class: "form-control"
  input.btn.btn-primary[type="submit" value="作成"]

app/views/companies/edit.html.slim
h1 記事編集

== render 'form'

=> link_to 'プレビュー', @company, class: "btn btn-info"
=> link_to '戻る', companies_path, class: "btn btn-dark"

app/views/companies/index.html.slim
h1 企業ページ
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="/companies/company1.jpeg" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 class="card-title">会社名</h4>
        <p class="card-text">テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト(５６文字)</p>
        <p class="card-text"><small class="text-muted">住所</small></p>
      </div>
    </div>
  </div>
</div>
table
  thead
    tr
      th 会社名
      th 情報
      th 住所
      th
      th
      th

  tbody
    - @companies.each do |company|
      .card.mb-3[style="max-width: 540px;"]
        .row.no-gutters
          .col-md-4
            = link_to company_path(company)
              img.card-img[src="/companies/company1.jpeg" alt="..."]
          .col-md-8
            .card-body
              h4.card-title
                = company.name
              p.card-text
                = company.info
              p.card-text
                small.text-muted
                  = company.zip
      tr
        td = company.name
        td = company.zip
        td = company.info
        td = link_to 'Show', company
        td = link_to 'Edit', edit_company_path(company)
        td = link_to 'Destroy', company, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to '記事を作る', new_company_path, class: "btn btn-primary", style: "margin-top: 10px;"

app/views/companies/new.html.slim
h1 企業記事の作成

== render 'form'

= link_to '戻る', companies_path, class: "btn btn-dark", style: "margin-top: 10px;"

app/views/companies/show.html.slim
p#notice = notice
.card.mb-3[style="max-width: 540px;"]
  .row.no-gutters
    .col-md-4
      img.card-img[src="/companies/company1.jpeg" alt="..."]
    .col-md-8
      .card-body
        h4.card-title =@company.name
        p.card-text =@company.info
        p.card-text
          small.text-muted =@company.zip
=> link_to '編集', edit_company_path(@company), class: "btn btn-primary"

=> link_to '戻る', companies_path, class: "btn btn-dark"

app/views/engineers/_form.html.slim
= form_for @engineer do |f|
  - if @engineer.errors.any?
    #error_explanation
      h2 = "#{pluralize(@engineer.errors.count, "error")} prohibited this engineer from being saved:"
      ul
        - @engineer.errors.full_messages.each do |message|
          li = message
  .input-group.mb-3
    .input-group-prepend
      span.input-group-text 氏名
    = f.text_field :name, class: "form-control"
  .input-group.mb-3
    .input-group-prepend
      span#inputGroup-sizing-default.input-group-text 社名
    = f.text_field :company, class: "form-control"
  .form-group
    label 紹介文
    = f.text_area :introducton, class: "form-control"
  input.btn.btn-primary[type="submit" value="作成"]

app/views/engineers/edit.html.slim
h1 記事編集

== render 'form'


=> link_to 'プレビュー', @engineer, class: "btn btn-info"
=> link_to '戻る', engineers_path, class: "btn btn-dark"

app/views/engineers/index.html.slim
h1 エンジニアページ
<div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="/engineers/engineer1.jpeg" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h4 class="card-title">氏名</h4>
        <p class="card-text">テキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキストテキスト(５６文字)</p>
        <p class="card-text"><small class="text-muted">会社名</small></p>
      </div>
    </div>
  </div>
</div>
table
  thead
    tr
      th エンジニア名
      th 会社名
      th 自己紹介
      th
      th
      th

  tbody
    - @engineers.each do |engineer|
      .card.mb-3[style="max-width: 540px;"]
        .row.no-gutters
          .col-md-4
            = link_to engineer_path(engineer)
              img.card-img[src="/engineers/engineer1.jpeg" alt="..."]
          .col-md-8
            .card-body
              h4.card-title
                = engineer.name
              p.card-text
                = engineer.introducton
              p.card-text
                small.text-muted
                  = engineer.company
      tr
        td = engineer.name
        td = engineer.company
        td = engineer.introducton
        td = link_to 'Show', engineer
        td = link_to 'Edit', edit_engineer_path(engineer)
        td = link_to 'Destroy', engineer, data: { confirm: 'Are you sure?' }, method: :delete

br

= link_to '記事を作る', new_engineer_path, class: "btn btn-primary", style: "margin-top: 10px;"

app/views/engineers/new.html.slim
h2 エンジニア記事作成

== render 'form'

= link_to '戻る', engineers_path, class: "btn btn-dark", style: "margin-top: 10px;"

app/views/engineers/show.html.slim
p#notice = notice
.card.mb-3[style="max-width: 540px;"]
  .row.no-gutters
    .col-md-4
      img.card-img[src="/engineers/engineer1.jpeg" alt="..."]
    .col-md-8
      .card-body
        h4.card-title =@engineer.name
        p.card-text =@engineer.introducton
        p.card-text
          small.text-muted =@engineer.company
=> link_to '編集', edit_engineer_path(@engineer), class: "btn btn-primary"

=> link_to '戻る', engineers_path, class: "btn btn-dark"

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | PoInfo
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  body
    hedder
      nav.navbar.navbar-expand-lg.navbar-light.bg-light
        a.navbar-brand[href="/"]
          | PoInfo
        button.navbar-toggler[type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation"]
          span.navbar-toggler-icon
        #navbarNavDropdown.collapse.navbar-collapse
          ul.navbar-nav
            li.nav-item
              = link_to root_path, class: "nav-link"
                | トップ 
            li.nav-item
              = link_to companies_path, class: "nav-link"
                | 企業
            li.nav-item
              = link_to engineers_path, class: "nav-link"
                | エンジニア
            li.nav-item
              = link_to about_path, class: "nav-link"
                | PoInfoとは
            li.nav-item
              = link_to about_path, class: "nav-link"
                | 管理者ログイン
    .container
      = yield
    footer.page-footer.font-small.blue.pt-4
  .container-fluid.text-center.text-md-left
    .row
      .col-md-6.mt-md-0.mt-3
        h5.text-uppercase style="color: red;"
          | PoInfo
        p
          | web系企業やエンジニアの情報を
        p
          | 伝えるメディア
      hr.clearfix.w-100.d-md-none.pb-3
      .col-md-3.mb-md-0.mb-3
        h5.text-uppercase
          | Links
        ul.list-unstyled
          li
            = link_to root_path, class: "nav-link"
              | トップ
          li
            = link_to companies_path, class: "nav-link"
              | 企業
          li
            = link_to engineers_path, class: "nav-link"
              | エンジニア
          li
            = link_to about_path, class: "nav-link"
              | PoInfoとは
          li
            = link_to about_path, class: "nav-link"
              | 管理者ログイン
  .footer-copyright.text-center.py-3
    | prsents by build開発合宿

app/views/top/index.html.slim
<div class="card-deck">
  <div class="card" >
    <img src="/companies/company1.jpeg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
  <div class="card" >
    <img src="/companies/company2.jpg" class="card-img-top" alt="..." >
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
  <div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="/engineers/engineer2.jpeg" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
  <div class="card" >
    <img src="/companies/company1.jpeg" class="card-img-top" alt="...">
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
  <div class="card" >
    <img src="/companies/company2.jpg" class="card-img-top" alt="..." >
    <div class="card-body">
      <h5 class="card-title">Card title</h5>
      <p class="card-text">Some quick example text to build on the card title and make up the bulk of the card's content.</p>
      <a href="#" class="btn btn-primary">Go somewhere</a>
    </div>
  </div>
  <div class="card mb-3" style="max-width: 540px;">
  <div class="row no-gutters">
    <div class="col-md-4">
      <img src="/engineers/engineer1.jpeg" class="card-img" alt="...">
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h5 class="card-title">Card title</h5>
        <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
        <p class="card-text"><small class="text-muted">Last updated 3 mins ago</small></p>
      </div>
    </div>
  </div>
</div>
</div>